# Generated by Django 5.0.6 on 2024-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
