# Generated by Django 5.0.6 on 2024-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=40)),
            ],
        ),
    ]
